---
# This playbook deploys SensoricNet grafana stack

- name: SensoricNet grafana instalation
  hosts: sn_grafana
  remote_user: root
  roles:
    - common
    - mqtt
    - grafana
    - influxdb
    - mqtt_forwarder
